// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzppwhp584Dj03XZGtdkI_wKb3Mvui3k',
    appId: '1:706837119484:web:a58547fe98108d596e7279',
    messagingSenderId: '706837119484',
    projectId: 'scene-e9b39',
    authDomain: 'scene-e9b39.firebaseapp.com',
    storageBucket: 'scene-e9b39.firebasestorage.app',
    measurementId: 'G-9E595531PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsw0cZxlfD7zaZqht4z3z0zI3FEse55xE',
    appId: '1:706837119484:android:9c88e3e781f6b7456e7279',
    messagingSenderId: '706837119484',
    projectId: 'scene-e9b39',
    storageBucket: 'scene-e9b39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlHD9qAPQHZ8kTvP16FI-5XZxxSO_saMw',
    appId: '1:706837119484:ios:5bd8e121c4a41d486e7279',
    messagingSenderId: '706837119484',
    projectId: 'scene-e9b39',
    storageBucket: 'scene-e9b39.firebasestorage.app',
    iosBundleId: 'com.example.scene',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlHD9qAPQHZ8kTvP16FI-5XZxxSO_saMw',
    appId: '1:706837119484:ios:5bd8e121c4a41d486e7279',
    messagingSenderId: '706837119484',
    projectId: 'scene-e9b39',
    storageBucket: 'scene-e9b39.firebasestorage.app',
    iosBundleId: 'com.example.scene',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgzppwhp584Dj03XZGtdkI_wKb3Mvui3k',
    appId: '1:706837119484:web:b84af4cd06baf4d36e7279',
    messagingSenderId: '706837119484',
    projectId: 'scene-e9b39',
    authDomain: 'scene-e9b39.firebaseapp.com',
    storageBucket: 'scene-e9b39.firebasestorage.app',
    measurementId: 'G-4VPZFB7JCV',
  );
}
